// +build !ios

package main

/*
#cgo CFLAGS: -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9  -O2 -Wall -W -fPIC -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_DESIGNER_LIB -DQT_UIPLUGIN_LIB -DQT_QUICKWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_XML_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB 
#cgo CXXFLAGS: -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9  -O2 -std=gnu++11 -Wall -W -fPIC -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_DESIGNER_LIB -DQT_UIPLUGIN_LIB -DQT_QUICKWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_XML_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB 
#cgo CXXFLAGS: -I../../dictee -I. -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtMultimedia.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtDesigner.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtUiPlugin.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtQuickWidgets.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtQuick.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtQml.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtNetwork.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtDBus.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtXml.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtTest.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/shirou/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang -F/Users/shirou/Qt5.8.0/5.8/clang_64/lib
#cgo LDFLAGS: -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9  -Wl,-rpath,/Users/shirou/Qt5.8.0/5.8/clang_64/lib
#cgo LDFLAGS:  -F/Users/shirou/Qt5.8.0/5.8/clang_64/lib -framework QtMultimediaWidgets -framework QtMultimedia -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtWidgets -framework QtDesigner -framework QtXml -framework QtQuickWidgets -framework QtQuick -framework QtQml -framework QtDBus -framework QtTest -framework Security -framework Foundation -framework ApplicationServices -framework OpenGL -framework AGL
*/
import "C"
